# ===================================================================
# This NSIS Script has been generated by SFX Tool
# Version 1.01
# Written by MuldeR (MuldeR2@GMX.de)
# Visit http://mulder.at.gg for further information!
#
# This application is based on NSIS v2.11 by Nullsoft
# ===================================================================



# -------------------------------------------------------------------
# Set Working Directory
# -------------------------------------------------------------------

!cd "C:\Program Files (x86)\MuldeR's Freeware\SFX Tool v1.01\Resources"


# -------------------------------------------------------------------
# Define Variables
# -------------------------------------------------------------------

var STARTMENU_FOLDER


# -------------------------------------------------------------------
# Choosing Compressor
# -------------------------------------------------------------------

SetCompressor LZMA
SetCompressorDictSize 32
SetCompress Auto
SetDatablockOptimize On


# -------------------------------------------------------------------
# SFX Definitions
# -------------------------------------------------------------------

!define SFX_AppID "{8FAB6A39-YAKD-49A0-BFBC-2675716E90E0}"; a unique ID for your SFX (It's real GUID)
!define SFX_BaseDir "C:\Program Files (x86)\MuldeR's Freeware\SFX Tool v1.01"; the SFX Tool install folder - do NOT edit!
!define SFX_Title "Yet Another Key Displayer"; the installer title
!define SFX_InstallDir "$PROGRAMFILES\Yet Another Key Displayer"; the *default* destination directory
!define SFX_OutFile "C:\Users\Jagailo\Desktop\YAKD 1.4 installer.exe"; the file to save the installer EXE to
!define SFX_IconFile "WinXP"; the installer icon
!define SFX_HeaderImage "Win"; the herader image
!define SFX_WizardImage "NSIS"; the wizard image


# -------------------------------------------------------------------
# Reserve Files
# -------------------------------------------------------------------

ReserveFile "Plugins\InstallOptions.dll"
ReserveFile "Plugins\LangDLL.dll"
ReserveFile "Plugins\StartMenu.dll"
ReserveFile "Plugins\UserInfo.dll"
ReserveFile "Contrib\Graphics\Wizard\${SFX_WizardImage}.bmp"
ReserveFile "Contrib\Graphics\Header\${SFX_HeaderImage}.bmp"
ReserveFile "Contrib\Graphics\Header\${SFX_HeaderImage}-R.bmp"
ReserveFile "Contrib\Modern UI\ioSpecial.ini"


# -------------------------------------------------------------------
# General Settings
# -------------------------------------------------------------------

XPStyle On
CRCCheck Force
ShowInstDetails Show
ShowUninstDetails Show
BrandingText "SFX Tool v1.01, NSIS v2.11"
Name "${SFX_Title}"
OutFile "${SFX_OutFile}"
InstallDir "${SFX_InstallDir}"
InstallDirRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${SFX_AppID}" "InstallDirectory"


# -------------------------------------------------------------------
# Modern Interface Settings
# -------------------------------------------------------------------

!include "MUI.nsh"

!define MUI_ICON "Contrib\Graphics\Icons\${SFX_IconFile}-Install.ico"
!define MUI_WELCOMEFINISHPAGE_BITMAP "Contrib\Graphics\Wizard\${SFX_WizardImage}.bmp"
!define MUI_HEADERIMAGE
!define MUI_HEADERIMAGE_BITMAP "Contrib\Graphics\Header\${SFX_HeaderImage}.bmp"
!define MUI_HEADERIMAGE_BITMAP_RTL "Contrib\Graphics\Header\${SFX_HeaderImage}-R.bmp"
!define MUI_ABORTWARNING
!define MUI_WELCOMEPAGE_TITLE_3LINES
!define MUI_FINISHPAGE_TITLE_3LINES
!define MUI_FINISHPAGE_NOAUTOCLOSE
!define MUI_LANGDLL_REGISTRY_ROOT "HKLM"
!define MUI_LANGDLL_REGISTRY_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${SFX_AppID}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "InstallLanguage"
!define MUI_LANGDLL_ALWAYSSHOW
!define MUI_FINISHPAGE_RUN "$INSTDIR\YAKD.exe"
!define MUI_FINISHPAGE_RUN_PARAMETERS ""
!define MUI_FINISHPAGE_LINK "https://github.com/Jagailo/YetAnotherKeyDisplayer"
!define MUI_FINISHPAGE_LINK_LOCATION "https://github.com/Jagailo/YetAnotherKeyDisplayer"
!define MUI_STARTMENUPAGE_REGISTRY_ROOT "HKLM"
!define MUI_STARTMENUPAGE_REGISTRY_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${SFX_AppID}"
!define MUI_STARTMENUPAGE_REGISTRY_VALUENAME "StartmenuFolder"
!define MUI_LICENSEPAGE_RADIOBUTTONS
!define MUI_UNICON "Contrib\Graphics\Icons\${SFX_IconFile}-Uninstall.ico"
!define MUI_UNWELCOMEFINISHPAGE_BITMAP "Contrib\Graphics\Wizard\${SFX_WizardImage}.bmp"
!define MUI_UNFINISHPAGE_NOAUTOCLOSE
!define MUI_UNABORTWARNING

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE "C:\Users\Jagailo\Documents\YetAnotherKeyDisplayer\LICENSE"
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_STARTMENU Application $STARTMENU_FOLDER
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH
!insertmacro MUI_UNPAGE_WELCOME
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_UNPAGE_FINISH


# -------------------------------------------------------------------
# Multi-Language Support
# -------------------------------------------------------------------

!insertmacro MUI_LANGUAGE "English"


# -------------------------------------------------------------------
# Install Files Section
# -------------------------------------------------------------------

Section
  SetOutPath "$INSTDIR"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\cs-CZ\Xceed.Wpf.AvalonDock.resources.dll"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\de\Xceed.Wpf.AvalonDock.resources.dll"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\es\Xceed.Wpf.AvalonDock.resources.dll"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\fr\Xceed.Wpf.AvalonDock.resources.dll"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\hu\Xceed.Wpf.AvalonDock.resources.dll"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\it\Xceed.Wpf.AvalonDock.resources.dll"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\ja-JP\Xceed.Wpf.AvalonDock.resources.dll"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\Newtonsoft.Json.dll"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\Newtonsoft.Json.xml"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\nl-BE\Xceed.Wpf.AvalonDock.resources.dll"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\pt-BR\Xceed.Wpf.AvalonDock.resources.dll"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\ro\Xceed.Wpf.AvalonDock.resources.dll"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\RTSSSharedMemoryNET.dll"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\RTSSSharedMemoryNET.xml"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\ru\Xceed.Wpf.AvalonDock.resources.dll"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\SharpVectors.Converters.Wpf.dll"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\SharpVectors.Converters.Wpf.xml"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\SharpVectors.Core.dll"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\SharpVectors.Core.xml"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\SharpVectors.Css.dll"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\SharpVectors.Css.xml"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\SharpVectors.Dom.dll"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\SharpVectors.Dom.xml"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\SharpVectors.Model.dll"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\SharpVectors.Model.xml"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\SharpVectors.Rendering.Gdi.dll"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\SharpVectors.Rendering.Gdi.xml"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\SharpVectors.Rendering.Wpf.dll"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\SharpVectors.Rendering.Wpf.xml"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\SharpVectors.Runtime.Wpf.dll"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\SharpVectors.Runtime.Wpf.xml"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\sv\Xceed.Wpf.AvalonDock.resources.dll"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\Xceed.Wpf.AvalonDock.dll"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\Xceed.Wpf.AvalonDock.Themes.Aero.dll"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\Xceed.Wpf.AvalonDock.Themes.Metro.dll"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\Xceed.Wpf.AvalonDock.Themes.VS2010.dll"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\Xceed.Wpf.Toolkit.dll"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\YAKD.exe"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\YAKD.exe.config"
  File /r "C:\Users\Jagailo\Desktop\YAKD 1.4\zh-Hans\Xceed.Wpf.AvalonDock.resources.dll"
SectionEnd


# -------------------------------------------------------------------
# Create Uninstaller Section
# -------------------------------------------------------------------

Section
  SetOutPath "$INSTDIR"
  WriteUninstaller "$INSTDIR\Uninstall.exe"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${SFX_AppID}" "DisplayName" "${SFX_Title}"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${SFX_AppID}" "DisplayIcon" "$\"$INSTDIR\Uninstall.exe$\""
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${SFX_AppID}" "UninstallString" "$\"$INSTDIR\Uninstall.exe$\""
  WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${SFX_AppID}" "NoModify" 1
  WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${SFX_AppID}" "NoRepair" 1
SectionEnd


# -------------------------------------------------------------------
# Startmenu Section
# -------------------------------------------------------------------

Section
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application

  SetShellVarContext all
  CreateDirectory "$SMPROGRAMS\$STARTMENU_FOLDER"
  CreateShortCut "$SMPROGRAMS\$STARTMENU_FOLDER\YAKD.lnk" "$INSTDIR\YAKD.exe"
  SetShellVarContext current

  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd


# -------------------------------------------------------------------
# Desktop Section
# -------------------------------------------------------------------

Section
  SetShellVarContext all
  CreateShortCut "$DESKTOP\YAKD.lnk" "$INSTDIR\YAKD.exe"
  SetShellVarContext current
SectionEnd


# -------------------------------------------------------------------
# Registry Section
# -------------------------------------------------------------------

Section
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${SFX_AppID}" "" "${SFX_Title}"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${SFX_AppID}" "InstallDirectory" "$INSTDIR"
SectionEnd


# -------------------------------------------------------------------
# Initialization Functions
# -------------------------------------------------------------------

Function .onInit
  InitPluginsDir

  ClearErrors
  UserInfo::GetName
  IfErrors RunTheInstaller
  Pop $0
  UserInfo::GetAccountType
  Pop $1

  StrCmp $1 "Admin" RunTheInstaller
  StrCmp $1 "Power" RunTheInstaller
  MessageBox MB_OK|MB_ICONSTOP|MB_TOPMOST "The user $\"$0$\" is not allowed to install this application.$\nPlease ask your administrator's permission !!!"
  Quit

  RunTheInstaller:
  !insertmacro MUI_LANGDLL_DISPLAY
FunctionEnd



# -------------------------------------------------------------------
# Uninstaller Section
# -------------------------------------------------------------------

Section "Uninstall"
  RMDir /r "$INSTDIR"

  !insertmacro MUI_STARTMENU_GETFOLDER Application $R0
  SetShellVarContext all
  RMDir /r "$SMPROGRAMS\$R0"
  SetShellVarContext current

  SetShellVarContext all
  Delete "$DESKTOP\YAKD.lnk"
  SetShellVarContext current

  DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${SFX_AppID}"
SectionEnd


# -------------------------------------------------------------------
# Uninstaller Initialization Function
# -------------------------------------------------------------------

Function un.onInit
  InitPluginsDir

  ClearErrors
  UserInfo::GetName
  IfErrors RunTheUninstaller
  Pop $0
  UserInfo::GetAccountType
  Pop $1

  StrCmp $1 "Admin" RunTheUninstaller
  StrCmp $1 "Power" RunTheUninstaller
  MessageBox MB_OK|MB_ICONSTOP|MB_TOPMOST "The user $\"$0$\" is not allowed to uninstall this application.$\nPlease ask your administrator's permission !!!"
  Quit

  RunTheUninstaller:
  !insertmacro MUI_LANGDLL_DISPLAY
FunctionEnd



# ===================================================================
# End of File
# ===================================================================
